/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cocktail;

import java.awt.*;
import java.awt.Toolkit;
/**
 *
 * @author lianeraji
 */
public class Homepage extends javax.swing.JFrame {
    private SoundPlayer soundPlayer;
   
    public Homepage() {
    soundPlayer = new SoundPlayer();
    soundPlayer.loadSound("Resources/Yummy2.wav");
    setVisible(true);
    initComponents();
   
    soundPlayer.playSound();

    Mute.addActionListener(this::MuteActionPerformed);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image cursorImage = toolkit.getImage(getClass().getResource("Resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
        soundPlayer.playSound(); 
        
        Mute.addActionListener(new java.awt.event.ActionListener() {
             @Override
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 MuteActionPerformed(evt);
    }
});

    }

    public SoundPlayer getSoundPlayer() {
    return soundPlayer;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        loginBtn = new javax.swing.JButton();
        Mute = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setBackground(new java.awt.Color(255, 188, 163));
        loginBtn.setFont(new java.awt.Font("Gujarati MT", 1, 13)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Lets start!");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 30));

        Mute.setBackground(new java.awt.Color(255, 188, 163));
        Mute.setForeground(new java.awt.Color(255, 255, 255));
        Mute.setText("♬");
        Mute.setOpaque(true);
        Mute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MuteMouseExited(evt);
            }
        });
        Mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuteActionPerformed(evt);
            }
        });
        getContentPane().add(Mute, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocktail/Resources/ddd-ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 201, 181));
        jLabel3.setFont(new java.awt.Font("Gujarati MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Welcome to Build-Your-Cocktail!<BR> Make a yummy cocktail as you wish!<br> But dont let it overflow! Enjoy!</html>");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 300, 150));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocktail/Resources/Homepage.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    this.setVisible(false); 
 Game game = new Game(soundPlayer);
 game.setVisible(true);


    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
         loginBtn.setBackground(new java.awt.Color(252,148,124));     
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor2.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
         
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
     
        loginBtn.setBackground(new java.awt.Color(255, 188, 163));
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMousePressed

    private void MuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuteActionPerformed
            
    soundPlayer.toggleMute();
    if (soundPlayer.isMuted()) {
        Mute.setText("✘♬"); 
    } else {
        Mute.setText("♬"); 
    }

    }//GEN-LAST:event_MuteActionPerformed

    private void MuteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MuteMouseEntered
        Mute.setBackground(new java.awt.Color(252,148,124));     
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor2.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
     
    setCursor(customCursor);
     if (soundPlayer.isMuted()) {
        Mute.setText("♬"); 
    } else {
        Mute.setText("✘♬"); 
    }
     
    }//GEN-LAST:event_MuteMouseEntered

    private void MuteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MuteMouseExited
     
        Mute.setBackground(new java.awt.Color(255, 188, 163));
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
     setCursor(customCursor);
    if (soundPlayer.isMuted()) {
        Mute.setText("✘♬"); 
    } else {
        Mute.setText("♬"); 
    }


    }//GEN-LAST:event_MuteMouseExited

    
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Mute;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables
}
