/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cocktail;

import java.awt.*;
import java.awt.Toolkit;
/**
 *
 * @author lianeraji
 */
public class LoginPage extends javax.swing.JFrame {
    private SoundPlayer soundPlayer;
   
    public LoginPage() {
    soundPlayer = new SoundPlayer();
    soundPlayer.loadSound("Resources/Yummy.wav");
    setVisible(true);
    initComponents();
   
    soundPlayer.playSound();

    Mute.addActionListener(this::MuteActionPerformed);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
        soundPlayer.playSound(); 
        
        Mute.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 MuteActionPerformed(evt);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        loginBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Mute = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setBackground(new java.awt.Color(255, 188, 163));
        loginBtn.setFont(new java.awt.Font("Gujarati MT", 1, 13)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Lets start!");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, 30));

        jLabel6.setBackground(new java.awt.Color(255, 188, 163));
        jLabel6.setFont(new java.awt.Font("Gujarati MT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 175, 159));
        jLabel6.setText(" ⊹Cocktail⊹ ");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 50));

        Mute.setBackground(new java.awt.Color(255, 188, 163));
        Mute.setForeground(new java.awt.Color(255, 255, 255));
        Mute.setText("♬");
        Mute.setOpaque(true);
        Mute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MuteMouseExited(evt);
            }
        });
        Mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuteActionPerformed(evt);
            }
        });
        getContentPane().add(Mute, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocktail/Resources/login.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    this.setVisible(false); 
    Homepage homePage = new Homepage(); 
    homePage.setVisible(true);
    if (!(soundPlayer.isMuted())) {
            soundPlayer.toggleMute();
    }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
         loginBtn.setBackground(new java.awt.Color(252,148,124));     
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor2.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
         
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
     
        loginBtn.setBackground(new java.awt.Color(255, 188, 163));
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMousePressed

    private void MuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuteActionPerformed
            
    soundPlayer.toggleMute();
    if (soundPlayer.isMuted()) {
        Mute.setText("✘♬"); 
    } else {
        Mute.setText("♬"); 
    }

    }//GEN-LAST:event_MuteActionPerformed

    private void MuteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MuteMouseEntered
        Mute.setBackground(new java.awt.Color(252,148,124));     
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor2.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
     
    setCursor(customCursor);
     if (soundPlayer.isMuted()) {
        Mute.setText("♬"); 
    } else {
        Mute.setText("✘♬"); 
    }
     
    }//GEN-LAST:event_MuteMouseEntered

    private void MuteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MuteMouseExited
     
        Mute.setBackground(new java.awt.Color(255, 188, 163));
        Toolkit toolkit = Toolkit.getDefaultToolkit();       
        Image cursorImage = toolkit.getImage(getClass().getResource("resources/cursor.png"));
        Cursor customCursor = toolkit.createCustomCursor(cursorImage, new Point(0, 0), "custom cursor");
        setCursor(customCursor);
     setCursor(customCursor);
    if (soundPlayer.isMuted()) {
        Mute.setText("✘♬"); 
    } else {
        Mute.setText("♬"); 
    }





    }//GEN-LAST:event_MuteMouseExited

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Mute;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables
}
